name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test for search
      run: cd search && go test -v 
    - name: Test for sort
      run: cd sort && go test -v 
    - name: Test for strings
      run: cd strings && go test -v 
    - name: Test for structure
      run: cd structure && go test -v 
    - name: Test for tree
      run: cd structure/tree && go test -v 
    - name: Test for heap
      run: cd structure/heap/ && go test -v 
    - name: Test for hashing
      run: cd hashing/ && go test -v 
